#!/bin/bash 

source /home/allouche/MySoftwares/NNMP-STM-Code/NNMP-STM/env.sh

export CUDA_VISIBLE_DEVICES='' # to force CPU use

python $NNMP_STM_CODEDIR/Utils/buildHistograms.py similarities.csv 20 hist
