#!/bin/bash

awk 'BEGIN{
i=1
}
{
	if(i>=2)
	{
		n=split($0,arr,",");
		ref=sprintf("ref_%d.png",arr[n])
		pred=sprintf("pred_%d.png",arr[n])
		refpredpref=sprintf("refpred_%d_SIS_%0.3f_SSIM_%0.3f_MS_SSIM_%0.3f",arr[n],arr[1],arr[2],arr[3])
		refpred=sprintf("%s.png",refpredpref)
		printf("echo convert +smush 5 -gravity center -background blue  %s %s +append %s\n",ref,pred,refpred)
		printf("convert +smush 5 -gravity center -background blue  %s %s +append %s\n",ref,pred,refpred)
	}
	i+=1
}' similarities.csv > xp
chmod u+x xp
cat xp
./xp
